[package]
name = "neuronal_dynamics_rs"
version = "0.1.0"
edition = "2021"
authors = ["AllenYolk <allen.yfhuang@gmail.com>"]

[dependencies]
clap = { version = "4.3.14", features = ["derive"] }
ode_solvers = "0.3.7"
plotters = "0.3.5"
